openapi: 3.1.0
info:
  title: Federated API Discovery API
  version: '0.1.0'
  description: This produces metadata about APIs published by public sector organisations
    in the UK
servers:
  - url: https://federated-api-model-spring-boot-sandbox.london.cloudapps.digital
    description: A deployment of the the API as an ephemeral sandbox environment
paths:
  "/apis":
    get:
      description: Gets metadata about APIs published by public sector organisations
        in the UK
      operationId: retrieveAll
      responses:
        '200':
          description: A list of API metadata objects
          content:
            application/vnd.uk.gov.api.v1alpha+json:
              schema:
                $ref: './bulk-metadata-response.json'
          headers:
            correlation-id:
              description: A unique identifier to allow for correlating requests
              required: true
              schema:
                type: string
                format: uuidv4
                pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
        '400':
          description: The request was malformed
          content:
            application/vnd.uk.gov.api.v1alpha+json:
              schema:
                $ref: './error-response.json'
          headers:
            correlation-id:
              description: A unique identifier to allow for correlating requests
              required: false
              schema:
                type: string
                format: uuidv4
                pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
        '406':
          description: The content-negotation, using the `Accept` header, failed
          content: {}
      parameters:
        - name: correlation-id
          in: header
          description: A unique identifier to allow for correlating requests
          required: false
          schema:
            type: string
            format: uuidv4
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[89abAB][a-fA-F0-9]{3}-[a-fA-F0-9]{12}"
