name: Test OpenAPI doc is valid on Pull Requests

on:
  pull_request:
    paths:
      - '.github/workflows/openapi-docs-pr.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"
      - "schemas/package.json"

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      - run: npm install
      - run: npm run lint:oas
